"""Adicionando tabela do estacionamento

Revision ID: ef67f68c77a9
Revises: e0bf85fbf814
Create Date: 2025-11-14 16:33:55.383933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef67f68c77a9'
down_revision: Union[str, Sequence[str], None] = 'e0bf85fbf814'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estacionamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('posicao', sa.String(), nullable=False),
    sa.Column('tipo_vaga', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('registros_estacionamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vaga_id', sa.Integer(), nullable=False),
    sa.Column('horario', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('entrou', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vaga_id'], ['estacionamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('tipo_do_veiculo', sa.String(), nullable=False))
    op.add_column('users', sa.Column('local', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'local')
    op.drop_column('users', 'tipo_do_veiculo')
    op.drop_table('registros_estacionamento')
    op.drop_table('estacionamentos')
    # ### end Alembic commands ###
